# BASIC
CC = g++
NAME = ts-timetracker
MAIN = main.cpp

# PATHS
CONTROLLERSPATH = ./controllers
CONTROLLERSHEADERPATH = $(CONTROLLERSPATH)/headers

# FILES
CONTROLLERHEADERS = $(CONTROLLERSHEADERPATH)/TS_Base.h $(CONTROLLERSHEADERPATH)/TS_Info.h
CONTROLLERS = $(CONTROLLERSPATH)/TS_Base.cpp $(CONTROLLERSPATH)/TS_Info.cpp

build:
	$(CC) -o $(NAME) $(MAIN) $(CONTROLLERS) $(CONTROLLERHEADERS)
